USE master;

IF NOT EXISTS(SELECT name FROM sysdatabases WHERE name = 'TP_CUATRIMESTRAL_DB')
BEGIN
    CREATE DATABASE TP_CUATRIMESTRAL_DB;
END

USE TP_CUATRIMESTRAL_DB;

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Cliente')
BEGIN
    CREATE TABLE Cliente (
        id_cliente INT IDENTITY(1,1) PRIMARY KEY,
        nombre VARCHAR(90) NOT NULL,
        apellido VARCHAR(90) NOT NULL,
        email VARCHAR(250) NOT NULL UNIQUE,
        telefono VARCHAR(20)
    );
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Marca')
BEGIN
    CREATE TABLE Marca (
        id_marca INT IDENTITY(1,1) PRIMARY KEY,
        nombre VARCHAR(90) NOT NULL
    );
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Categoria')
BEGIN
    CREATE TABLE Categoria (
        id_categoria INT   
 IDENTITY(1,1) PRIMARY KEY,
        nombre VARCHAR(90) NOT NULL
    );
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Producto')
BEGIN
    CREATE TABLE Producto (
        id_producto INT IDENTITY(1,1) PRIMARY KEY,
        nombre VARCHAR(155) NOT NULL,
        descripcion VARCHAR(250),
        precio DECIMAL(10,2) NOT NULL,
        id_marca INT FOREIGN KEY REFERENCES Marca(id_marca),
        id_categoria INT FOREIGN KEY REFERENCES Categoria(id_categoria),
        porcentaje_descuento TINYINT DEFAULT 0,
        stock INT NOT NULL DEFAULT 0
    );
END